springdoc:
  swagger-ui:
    configUrl: "/swagger-config.json"
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
      routes:
        - id: auth-server-no-filter
          uri: lb://auth-service
          predicates:
            - Path=/api/identity/**,


        - id: admin-panel
          uri: lb://admin-service
          predicates:
            - Path=/api/support-messages/**,/api/support-messages,/api/result-messages,/api/result-messages/**

        - id: main-server
          uri: lb://main-service
          predicates:
            - Path=/api/**
          filters:
            - name: AuthenticationFilter
          #- id: auth-server-registration
          #  uri: lb://authorization-service
          #  predicates:
          #    - Path=/api/identity/registration
          #  filters:
          #    - name: AuthenticationFilter
          #      args:
          #        requiredRole: ROLE_ADMIN
logging:
  level:
    org.springframework.cloud.gateway: TRACE